name: Kwiki-Spork
version: 0.10
abstract: Kwiki Spork Plugin
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.31
  Spork: 0.18
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
